CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(36) PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE,
    project_ids VARCHAR(36) DEFAULT NULL,
    FOREIGN KEY (project_ids) REFERENCES projects(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
